# 模式匹配和多个存储库
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kouhanyao/SpringCloudConfigTest.git #当模式匹配不成功时,调用该路径
          repos:
            Teacher:
              pattern: user/dev #对应用程序进行模式匹配,模式格式是带有通配符的{application}/{profile}名称的逗号分隔列表（可能需要引用以通配符开头的模式）
              uri: https://github.com/forezp/SpringcloudConfig.git
              searchPaths: respo